version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    container_name: mysql
    volumes: ['./assets:/assets', './mysql:/var/lib/mysql']
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: `user should fill out`
      MYSQL_USER: `user should fill out`
      MYSQL_PASSWORD: `user should fill out`
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wp
    ports:
      - '80:80'
    restart: always
    volumes: ['./html:/var/www/html/']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: `user should fill out`
      WORDPRESS_DB_USER: `user should fill out`
      WORDPRESS_DB_PASSWORD: `user should fill out`
      WP_ENVIRONMENT_TYPE: 'local'
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data: